import shutil
import subprocess
from dataclasses import dataclass
import json
from typing import Protocol

from openai import OpenAI

from app.core.config import Settings

REPORT_INSTRUCTIONS = (
    "You are a requirements evaluation assistant. "
    "Follow the rubric and produce the final answer in Chinese Markdown using the template."
)
CODEX_CLI_TIMEOUT_SECONDS = 300


class ModelClient(Protocol):
    def generate_text(self, *, instructions: str, input_text: str) -> str: ...

    def generate_report(self, *, skill_text: str, template_text: str, packet_text: str) -> str: ...


def _build_tagged_prompt(*, skill_text: str, template_text: str, packet_text: str) -> str:
    return (
        "[SKILL]\n"
        f"{skill_text}\n\n"
        "[TEMPLATE]\n"
        f"{template_text}\n\n"
        "[PACKET]\n"
        f"{packet_text}\n"
    )


class StaticModelClient:
    def generate_text(self, *, instructions: str, input_text: str) -> str:
        if "[TASK]\nPARTIAL_REVIEW" in input_text:
            shard_packet = _extract_tagged_json(input_text, "SHARD_PACKET_JSON")
            results = []
            for group in shard_packet.get("groups", []):
                dr_scores = [
                    {
                        "dr_id": dr_item["id"],
                        "dr_name": dr_item["name"],
                        "score": 24,
                    }
                    for dr_item in group.get("dr_items", [])
                ]
                results.append(
                    {
                        "or_id": group["id"],
                        "or_name": group["name"],
                        "or_total_score": 60,
                        "grade": "中等",
                        "or_part_score": 22,
                        "dr_scores": dr_scores,
                        "dr_average_score": 24 if dr_scores else 0,
                        "traceability_score": 14,
                        "review_conclusion": "Mock partial review generated by StaticModelClient.",
                        "design_review_readiness": "有条件进入",
                        "development_readiness": "有条件进入",
                        "test_design_readiness": "有条件进入",
                        "blocking_issues": [],
                        "triggered_red_line_rules": [],
                        "evidence_bullets": ["Mock evidence"],
                        "red_flags": [],
                        "missing_items": [],
                        "revision_actions": ["补充用户价值", "补充测试要点"],
                    }
                )
            return json.dumps(
                {
                    "shard_id": shard_packet.get("shard_id", "shard-000"),
                    "sheet_name": shard_packet.get("source_info", {}).get("sheet_name"),
                    "cross_shard_notes": {"weak_dimensions": ["OR-用户价值", "DR-可测试性"]},
                    "or_results": results,
                },
                ensure_ascii=False,
                indent=2,
            )
        return "# Mock Report\n\nReplace this client with the real model integration.\n"

    def generate_report(self, *, skill_text: str, template_text: str, packet_text: str) -> str:
        return self.generate_text(
            instructions=REPORT_INSTRUCTIONS,
            input_text=_build_tagged_prompt(
                skill_text=skill_text,
                template_text=template_text,
                packet_text=packet_text,
            ),
        )


@dataclass
class OpenAIModelClient:
    model_name: str
    client: OpenAI

    def generate_text(self, *, instructions: str, input_text: str) -> str:
        response = self.client.responses.create(
            model=self.model_name,
            instructions=instructions,
            input=input_text,
        )
        if not response.output_text:
            raise RuntimeError("OpenAI response did not contain output_text.")
        return response.output_text

    def generate_report(self, *, skill_text: str, template_text: str, packet_text: str) -> str:
        return self.generate_text(
            instructions=REPORT_INSTRUCTIONS,
            input_text=_build_tagged_prompt(
                skill_text=skill_text,
                template_text=template_text,
                packet_text=packet_text,
            ),
        )


@dataclass
class CodexModelClient:
    model_name: str

    def generate_text(self, *, instructions: str, input_text: str) -> str:
        prompt = f"{instructions}\n\n{input_text}"
        try:
            result = subprocess.run(
                ["codex", "exec", "--model", self.model_name, prompt],
                capture_output=True,
                text=True,
                timeout=CODEX_CLI_TIMEOUT_SECONDS,
            )
        except subprocess.TimeoutExpired as exc:
            raise RuntimeError(
                f"Codex CLI timed out after {CODEX_CLI_TIMEOUT_SECONDS} seconds."
            ) from exc
        if result.returncode != 0:
            stderr = result.stderr.strip() or "no stderr output"
            raise RuntimeError(
                f"Codex CLI failed with exit code {result.returncode}: {stderr}"
            )

        report = result.stdout.strip()
        if not report:
            raise RuntimeError("Codex CLI returned empty stdout.")
        return report

    def generate_report(self, *, skill_text: str, template_text: str, packet_text: str) -> str:
        return self.generate_text(
            instructions=REPORT_INSTRUCTIONS,
            input_text=_build_tagged_prompt(
                skill_text=skill_text,
                template_text=template_text,
                packet_text=packet_text,
            ),
        )


def _extract_tagged_json(text: str, tag: str) -> dict:
    start_marker = f"[{tag}]\n"
    start = text.find(start_marker)
    if start == -1:
        return {}
    payload = text[start + len(start_marker):]
    end = payload.find("\n[")
    if end != -1:
        payload = payload[:end]
    try:
        return json.loads(payload)
    except json.JSONDecodeError:
        return {}


@dataclass(frozen=True)
class ResolvedModelRuntime:
    provider_name: str
    model_name: str
    api_key: str | None = None
    base_url: str | None = None


NO_MODEL_PROVIDER_ERROR_MESSAGE = (
    "No model provider is available. Checked OPENAI_API_KEY, ZHIPU_API_KEY, "
    "Codex CLI availability on PATH via `codex`, and "
    "REQUIREMENTS_EVALUATOR_DEBUG_FALLBACK=1 for local debugging. "
    "The static placeholder runtime is not valid for application startup."
)


def resolve_model_runtime(settings: Settings) -> ResolvedModelRuntime:
    if settings.openai_api_key is not None:
        return ResolvedModelRuntime(
            provider_name="openai",
            model_name=settings.openai_model,
            api_key=settings.openai_api_key,
            base_url=settings.openai_base_url,
        )
    if settings.zhipu_api_key is not None:
        return ResolvedModelRuntime(
            provider_name="zhipu",
            model_name=settings.zhipu_model,
            api_key=settings.zhipu_api_key,
            base_url=settings.zhipu_base_url,
        )
    if shutil.which("codex") is not None:
        return ResolvedModelRuntime(
            provider_name="codex",
            model_name=settings.codex_model,
        )
    if settings.debug_fallback_enabled:
        return ResolvedModelRuntime(provider_name="debug", model_name="debug-fallback")
    return ResolvedModelRuntime(provider_name="static", model_name="static")


def validate_model_runtime_available(settings: Settings) -> ResolvedModelRuntime:
    runtime = resolve_model_runtime(settings)
    if runtime.provider_name == "static":
        raise RuntimeError(NO_MODEL_PROVIDER_ERROR_MESSAGE)
    return runtime


def model_provider_name(settings: Settings) -> str:
    return resolve_model_runtime(settings).provider_name


def build_model_client(settings: Settings) -> ModelClient:
    runtime = resolve_model_runtime(settings)
    if runtime.api_key is not None and runtime.base_url is not None:
        return OpenAIModelClient(
            model_name=runtime.model_name,
            client=OpenAI(api_key=runtime.api_key, base_url=runtime.base_url),
        )
    if runtime.provider_name == "codex":
        return CodexModelClient(model_name=runtime.model_name)
    return StaticModelClient()
